/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthenticatedRouteRouteImport } from './app/routes/_authenticated/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './app/routes/_authenticated/dashboard'
import { Route as ApiProjectsIndexRouteImport } from './app/routes/api/projects/index'
import { Route as AuthenticatedApiTokensIndexRouteImport } from './app/routes/_authenticated/api-tokens.index'
import { Route as AuthenticatedProjectsCreateRouteImport } from './app/routes/_authenticated/projects.create'
import { Route as AuthenticatedApiTokensCreateRouteImport } from './app/routes/_authenticated/api-tokens.create'
import { Route as ApiProjectsProjectIdIndexRouteImport } from './app/routes/api/projects.$projectId/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './app/routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdImportRouteImport } from './app/routes/_authenticated/projects.$projectId.import'
import { Route as ApiAuthCallbackMicrosoftEntraIdIndexRouteImport } from './app/routes/api/auth/callback/microsoft-entra-id/index'
import { Route as ApiProjectsProjectIdBranchBranchIdIndexRouteImport } from './app/routes/api/projects.$projectId/branch.$branchId/index'
import { Route as AuthenticatedProjectsProjectIdBranchBranchIdStudioV2RouteImport } from './app/routes/_authenticated/projects.$projectId.branch.$branchId.studio-v2'
import { Route as AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRouteImport } from './app/routes/_authenticated/projects.$projectId.branch.$branchId.config.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiTokensIndexRoute =
  AuthenticatedApiTokensIndexRouteImport.update({
    id: '/api-tokens/',
    path: '/api-tokens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiTokensCreateRoute =
  AuthenticatedApiTokensCreateRouteImport.update({
    id: '/api-tokens/create',
    path: '/api-tokens/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiProjectsProjectIdIndexRoute =
  ApiProjectsProjectIdIndexRouteImport.update({
    id: '/api/projects/$projectId/',
    path: '/api/projects/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdImportRoute =
  AuthenticatedProjectsProjectIdImportRouteImport.update({
    id: '/projects/$projectId/import',
    path: '/projects/$projectId/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthCallbackMicrosoftEntraIdIndexRoute =
  ApiAuthCallbackMicrosoftEntraIdIndexRouteImport.update({
    id: '/api/auth/callback/microsoft-entra-id/',
    path: '/api/auth/callback/microsoft-entra-id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdBranchBranchIdIndexRoute =
  ApiProjectsProjectIdBranchBranchIdIndexRouteImport.update({
    id: '/api/projects/$projectId/branch/$branchId/',
    path: '/api/projects/$projectId/branch/$branchId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route =
  AuthenticatedProjectsProjectIdBranchBranchIdStudioV2RouteImport.update({
    id: '/projects/$projectId/branch/$branchId/studio-v2',
    path: '/projects/$projectId/branch/$branchId/studio-v2',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute =
  AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRouteImport.update({
    id: '/projects/$projectId/branch/$branchId/config/edit',
    path: '/projects/$projectId/branch/$branchId/config/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api-tokens/create': typeof AuthenticatedApiTokensCreateRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/api-tokens': typeof AuthenticatedApiTokensIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/projects/$projectId/import': typeof AuthenticatedProjectsProjectIdImportRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdIndexRoute
  '/api/auth/callback/microsoft-entra-id': typeof ApiAuthCallbackMicrosoftEntraIdIndexRoute
  '/projects/$projectId/branch/$branchId/studio-v2': typeof AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route
  '/api/projects/$projectId/branch/$branchId': typeof ApiProjectsProjectIdBranchBranchIdIndexRoute
  '/projects/$projectId/branch/$branchId/config/edit': typeof AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api-tokens/create': typeof AuthenticatedApiTokensCreateRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/api-tokens': typeof AuthenticatedApiTokensIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/projects/$projectId/import': typeof AuthenticatedProjectsProjectIdImportRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdIndexRoute
  '/api/auth/callback/microsoft-entra-id': typeof ApiAuthCallbackMicrosoftEntraIdIndexRoute
  '/projects/$projectId/branch/$branchId/studio-v2': typeof AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route
  '/api/projects/$projectId/branch/$branchId': typeof ApiProjectsProjectIdBranchBranchIdIndexRoute
  '/projects/$projectId/branch/$branchId/config/edit': typeof AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/api-tokens/create': typeof AuthenticatedApiTokensCreateRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/api-tokens/': typeof AuthenticatedApiTokensIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/_authenticated/projects/$projectId/import': typeof AuthenticatedProjectsProjectIdImportRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/api/projects/$projectId/': typeof ApiProjectsProjectIdIndexRoute
  '/api/auth/callback/microsoft-entra-id/': typeof ApiAuthCallbackMicrosoftEntraIdIndexRoute
  '/_authenticated/projects/$projectId/branch/$branchId/studio-v2': typeof AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route
  '/api/projects/$projectId/branch/$branchId/': typeof ApiProjectsProjectIdBranchBranchIdIndexRoute
  '/_authenticated/projects/$projectId/branch/$branchId/config/edit': typeof AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api-tokens/create'
    | '/projects/create'
    | '/api-tokens'
    | '/api/projects'
    | '/projects/$projectId/import'
    | '/projects/$projectId'
    | '/api/projects/$projectId'
    | '/api/auth/callback/microsoft-entra-id'
    | '/projects/$projectId/branch/$branchId/studio-v2'
    | '/api/projects/$projectId/branch/$branchId'
    | '/projects/$projectId/branch/$branchId/config/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api-tokens/create'
    | '/projects/create'
    | '/api-tokens'
    | '/api/projects'
    | '/projects/$projectId/import'
    | '/projects/$projectId'
    | '/api/projects/$projectId'
    | '/api/auth/callback/microsoft-entra-id'
    | '/projects/$projectId/branch/$branchId/studio-v2'
    | '/api/projects/$projectId/branch/$branchId'
    | '/projects/$projectId/branch/$branchId/config/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/api-tokens/create'
    | '/_authenticated/projects/create'
    | '/_authenticated/api-tokens/'
    | '/api/projects/'
    | '/_authenticated/projects/$projectId/import'
    | '/_authenticated/projects/$projectId/'
    | '/api/projects/$projectId/'
    | '/api/auth/callback/microsoft-entra-id/'
    | '/_authenticated/projects/$projectId/branch/$branchId/studio-v2'
    | '/api/projects/$projectId/branch/$branchId/'
    | '/_authenticated/projects/$projectId/branch/$branchId/config/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiProjectsProjectIdIndexRoute: typeof ApiProjectsProjectIdIndexRoute
  ApiAuthCallbackMicrosoftEntraIdIndexRoute: typeof ApiAuthCallbackMicrosoftEntraIdIndexRoute
  ApiProjectsProjectIdBranchBranchIdIndexRoute: typeof ApiProjectsProjectIdBranchBranchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-tokens/': {
      id: '/_authenticated/api-tokens/'
      path: '/api-tokens'
      fullPath: '/api-tokens'
      preLoaderRoute: typeof AuthenticatedApiTokensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-tokens/create': {
      id: '/_authenticated/api-tokens/create'
      path: '/api-tokens/create'
      fullPath: '/api-tokens/create'
      preLoaderRoute: typeof AuthenticatedApiTokensCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/projects/$projectId/': {
      id: '/api/projects/$projectId/'
      path: '/api/projects/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/import': {
      id: '/_authenticated/projects/$projectId/import'
      path: '/projects/$projectId/import'
      fullPath: '/projects/$projectId/import'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/callback/microsoft-entra-id/': {
      id: '/api/auth/callback/microsoft-entra-id/'
      path: '/api/auth/callback/microsoft-entra-id'
      fullPath: '/api/auth/callback/microsoft-entra-id'
      preLoaderRoute: typeof ApiAuthCallbackMicrosoftEntraIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/branch/$branchId/': {
      id: '/api/projects/$projectId/branch/$branchId/'
      path: '/api/projects/$projectId/branch/$branchId'
      fullPath: '/api/projects/$projectId/branch/$branchId'
      preLoaderRoute: typeof ApiProjectsProjectIdBranchBranchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/branch/$branchId/studio-v2': {
      id: '/_authenticated/projects/$projectId/branch/$branchId/studio-v2'
      path: '/projects/$projectId/branch/$branchId/studio-v2'
      fullPath: '/projects/$projectId/branch/$branchId/studio-v2'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBranchBranchIdStudioV2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/branch/$branchId/config/edit': {
      id: '/_authenticated/projects/$projectId/branch/$branchId/config/edit'
      path: '/projects/$projectId/branch/$branchId/config/edit'
      fullPath: '/projects/$projectId/branch/$branchId/config/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedApiTokensCreateRoute: typeof AuthenticatedApiTokensCreateRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedApiTokensIndexRoute: typeof AuthenticatedApiTokensIndexRoute
  AuthenticatedProjectsProjectIdImportRoute: typeof AuthenticatedProjectsProjectIdImportRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route: typeof AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route
  AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute: typeof AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedApiTokensCreateRoute: AuthenticatedApiTokensCreateRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedApiTokensIndexRoute: AuthenticatedApiTokensIndexRoute,
  AuthenticatedProjectsProjectIdImportRoute:
    AuthenticatedProjectsProjectIdImportRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
  AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route:
    AuthenticatedProjectsProjectIdBranchBranchIdStudioV2Route,
  AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute:
    AuthenticatedProjectsProjectIdBranchBranchIdConfigEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiProjectsProjectIdIndexRoute: ApiProjectsProjectIdIndexRoute,
  ApiAuthCallbackMicrosoftEntraIdIndexRoute:
    ApiAuthCallbackMicrosoftEntraIdIndexRoute,
  ApiProjectsProjectIdBranchBranchIdIndexRoute:
    ApiProjectsProjectIdBranchBranchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
