services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: rephrase
      POSTGRES_PASSWORD: rephrase
      POSTGRES_DB: rephrase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
