services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rewrite
      POSTGRES_PASSWORD: rewrite
      POSTGRES_DB: rewrite
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
